os: linux
language: python
python:
  - "3.8"

services:
  - docker

install: pip install docker-compose flake8

jobs:
  include:
    - stage: "Tests"
      name: "API Tests"
      script: docker-compose run --rm app sh -c "python manage.py test --parallel"
    - stage: "Lint"
      name: "API Lint"
      script: cd app/ && flake8