// AUTH
export const LOG_IN = "LOG_IN";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const LOCALSTORAGE_LOG_IN = "LOCALSTORAGE_LOG_IN";
export const LOCALSTORAGE_LOG_IN_FAILED = "LOCALSTORAGE_LOG_IN_FAILED";
export const LOG_OUT = "LOG_OUT";

// USER
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const UPLOAD_PROFILE_PICTURE = "UPLOAD_PROFILE_PICTURE";
export const GET_USER_ADVERTS = "GET_USER_ADVERTS";
export const GET_USER_CONVERSATIONS = "GET_USER_CONVERSATIONS";
export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE";
export const EDIT_USER_PROFILE_FAILED = "EDIT_USER_PROFILE_FAILED";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

// ADVERT
export const GET_ADVERTS = "GET_ADVERTS";
export const GET_ADVERT = "GET_ADVERT";

// CURRENT ADVERT
export const CREATE_ADVERT = "CREATE_ADVERT";
export const CREATE_ADVERT_FAILED = "CREATE_ADVERT_FAILED";
export const EDIT_ADVERT = "EDIT_ADVERT";
export const EDIT_ADVERT_FAILED = "EDIT_ADVERT_FAILED";
export const UPLOAD_ADVERT_IMAGE = "UPLOAD_ADVERT_IMAGE";
export const DELETE_ADVERT_IMAGE = "DELETE_ADVERT_IMAGE";
